OMEGA_UCB_STUMP = r"$\omega$-UCB ($\rho = {}$)"
OMEGA_UCB_1_64 = r"$\omega$-UCB ($\rho = \frac{1}{64}$)"
OMEGA_UCB_1_32 = r"$\omega$-UCB ($\rho = \frac{1}{32}$)"
OMEGA_UCB_1_16 = r"$\omega$-UCB ($\rho = \frac{1}{16}$)"
OMEGA_UCB_1_8 = r"$\omega$-UCB ($\rho = \frac{1}{8}$)"
OMEGA_UCB_1_6 = r"$\omega$-UCB ($\rho = \frac{1}{6}$)"
OMEGA_UCB_1_5 = r"$\omega$-UCB ($\rho = \frac{1}{5}$)"
OMEGA_UCB_1_4 = r"$\omega$-UCB ($\rho = \frac{1}{4}$)"
OMEGA_UCB_1_3 = r"$\omega$-UCB ($\rho = \frac{1}{3}$)"
OMEGA_UCB_1_2 = r"$\omega$-UCB ($\rho = \frac{1}{2}$)"
OMEGA_UCB_1 = r"$\omega$-UCB ($\rho = 1$)"
OMEGA_UCB_2 = r"$\omega$-UCB ($\rho = 2$)"
OMEGA_UCB_3 = r"$\omega$-UCB ($\rho = 3$)"
OMEGA_UCB_4 = r"$\omega$-UCB ($\rho = 4$)"
OMEGA_UCB_ = r"$\omega$-UCB"

ETA_UCB_STUMP = r"$\eta$-UCB ($\rho = {}$)"
ETA_UCB_1_64 = r"$\omega$-UCB ($\rho = \frac{1}{64}$)"
ETA_UCB_1_32 = r"$\eta$-UCB ($\rho = \frac{1}{32}$)"
ETA_UCB_1_16 = r"$\eta$-UCB ($\rho = \frac{1}{16}$)"
ETA_UCB_1_8 = r"$\eta$-UCB ($\rho = \frac{1}{8}$)"
ETA_UCB_1_6 = r"$\eta$-UCB ($\rho = \frac{1}{6}$)"
ETA_UCB_1_5 = r"$\eta$-UCB ($\rho = \frac{1}{5}$)"
ETA_UCB_1_4 = r"$\eta$-UCB ($\rho = \frac{1}{4}$)"
ETA_UCB_1_3 = r"$\eta$-UCB ($\rho = \frac{1}{3}$)"
ETA_UCB_1_2 = r"$\eta$-UCB ($\rho = \frac{1}{2}$)"
ETA_UCB_1 = r"$\eta$-UCB ($\rho = 1$)"
ETA_UCB_2 = r"$\eta$-UCB ($\rho = 2$)"
ETA_UCB_3 = r"$\eta$-UCB ($\rho = 3$)"
ETA_UCB_4 = r"$\eta$-UCB ($\rho = 4$)"
ETA_UCB_ = r"$\eta$-UCB"

MUCB = "m-UCB"
CUCB = "c-UCB"
IUCB = "i-UCB"
BTS = "BTS"
UCB_SC = "UCB-SC"
UCB_SC_PLUS = "UCB-SC+"
BUDGET_UCB = "B-UCB"
B_GREEDY = "b-greedy"